CREATE TABLE IF NOT EXISTS EMPLOYEES(
    ID TEXT PRIMARY KEY,
    NAME TEXT,
    SALARY INTEGER,
    PHONE_NUMBER TEXT
);

INSERT INTO EMPLOYEES(ID,NAME,SALARY,PHONE_NUMBER) VALUES
('01','MARK',4000,'******'),
('02','RUBEN',7000,'******'),
('03','CASSIDY',6000,'******'),
('04','JONATHAN',8000,'******');

SELECT * FROM EMPLOYEES